### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/php#330]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/php/issues/321)
- [x] [Add key features](https://github.com/exercism/php/issues/322)
- [x] [Add tags](https://github.com/exercism/php/issues/323)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/php/issues/324)
- [x] [Update status of track](https://github.com/exercism/php/issues/329)
- [x] [Update status of Concept Exercises](https://github.com/exercism/php/issues/328)
- [x] [Pass linting checks](https://github.com/exercism/php/issues/325)
- [x] [Build Test Runner](https://github.com/exercism/php/issues/326)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/php/issues/327) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by petemcfarlane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Laravel security update](https://trello.com/c/682GdOvB/1360-laravel-security-update)
