### ISSUE TITLE
Tracking: Missing exercises from problem specifications

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#629]
Directly from `configlet info`.

There are 44 non-deprecated exercises in `exercism/problem-specifications` that are both unimplemented and not in the track config `exercises.foregone` array:

With canonical data:

- [ ] bottle-song
- [ ] circular-buffer
- [ ] complex-numbers
- [ ] custom-set
- [ ] dominoes
- [ ] eliuds-eggs
- [ ] food-chain
- [ ] forth
- [ ] go-counting
- [ ] grep
- [ ] house
- [ ] isbn-verifier
- [ ] killer-sudoku-helper
- [ ] kindergarten-garden
- [ ] knapsack
- [ ] ledger
- [ ] micro-blog
- [ ] ~~parallel-letter-frequency~~ (PHP does not support parallel execution)
- [ ] pov
- [ ] pythagorean-triplet
- [ ] rational-numbers
- [ ] react
- [ ] rectangles
- [ ] rest-api
- [ ] rotational-cipher
- [ ] saddle-points
- [ ] satellite
- [ ] secret-handshake
- [ ] sgf-parsing
- [ ] spiral-matrix
- [ ] square-root
- [ ] state-of-tic-tac-toe
- [ ] strain
- [ ] sublist
- [ ] two-bucket
- [ ] word-search
- [ ] zipper

Without canonical data:

- [ ] dot-dsl
- [ ] error-handling
- [ ] hangman
- [ ] lens-person
- [ ] paasio
- [ ] simple-linked-list
- [ ] tree-building

**Comment by neenjaw** [comment]
I suggest to add these to the forgone exercises:
- the unimplemented sing-song exercises like bottle-song
- math-centric exercises like complex-numbers, rational-numbers, Pythagorean-triplet -- these are niche topics which exclude a lot of users if you aren't already familiar with these math concepts. 
- rest-api -- very old exercise, poorly defined
- zipper -- doesn't make very much sense in a non-functional language.

**Comment by tomasnorre** [comment]
Wauw, I didn't expect it to be this many exercises missing, then there is still work to do :) I Only had the list from #48in24 in mind. 
 
Would it be possible to add a priority to them? High, Medium, Low would be enough I think.

**Comment by mk-mxp** [comment]
> Would it be possible to add a priority to them? High, Medium, Low would be enough I think.

I'm too busy to look at them in more detail at the moment. But that was my plan. And also mark those as _foregone_ that cannot or should not be implemented.

**Comment by tomasnorre** [comment]
I have added a PR for 
* https://github.com/exercism/php/pull/641

**Comment by resu-xuniL** [comment]
I have added a PR for 
* https://github.com/exercism/php/pull/1001
* https://github.com/exercism/php/pull/1003
* https://github.com/exercism/php/pull/1004
* https://github.com/exercism/php/pull/1006
* https://github.com/exercism/php/pull/1007
* https://github.com/exercism/php/pull/1011

PS: I left the `difficulty` at `1` for all of these.

**Comment by mk-mxp** [comment]
Please be aware: The list in the issue description is not very up-to-date. New exercises have been defined, some are renamed, some have canonical data now. Run `configlet info` for up-to-date information.

**Comment by resu-xuniL** [comment]
I have added a PR for:

* https://github.com/exercism/php/pull/1034
* https://github.com/exercism/php/pull/1039

**Comment by resu-xuniL** [comment]
Added a PR for:

* https://github.com/exercism/php/pull/1048

**Comment by resu-xuniL** [comment]
Added a PR for:

* https://github.com/exercism/php/pull/1049

**Comment by resu-xuniL** [comment]
Added a PR for:

* https://github.com/exercism/php/pull/1052

**Comment by resu-xuniL** [comment]
Added a PR for:

* https://github.com/exercism/php/pull/1053
