### ISSUE TITLE
Tracking: Test generator MVP

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#631]
Test generator MVP to use after `configlet generate` for practice exercises:

- [ ] Integrate [POC test generator](https://forum.exercism.org/t/poc-for-autogenerated-tests-for-php-track/9692) into separate directory, so it is not installed in CI
- [ ] Add a parameter to choose the exercise by slug
- [ ] Use local `configlet` cached problem specification repository as information source
- [ ] Write to already created `/exercises/practice/${slug}/{PascalCaseSlug}.php`
- [ ] Have testdox with description
- [ ] Have UUID in DocBlock
- [ ] Have all tests marked incomplete
- [ ] Have `$input`, `$expected`
- [ ] Have `$subject = new ${PascalSlug};`, `$actual = $subject->${property}();` and `assertSame();`
- [ ] Have test class DocBlock with "PHP track rules"

**Comment by mk-mxp** [comment]
@tomasnorre Did you add some functionality to your local copy of the test generator that you would want to have here, too? I think I'll find time on the weekend to take some of the steps outlined here and would be happy to integrate the "latest" version.
