### ISSUE TITLE
Tracking: Syncing exercises for #48in24

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#684]
For `#48in24` exercises should be synced a few days before they are featured. Exercism core team polishes these exercises some time in advance (see [`#48in24` forum threads](https://forum.exercism.org/c/exercism/48in24/364)), but there is no announcement of being ready, yet. So I think, we should **not** work through this list as fast as possible, only sync them a maximum of 2 weeks ahead of the dates.

Most of these exercises also appear in #628.

To sync an exercise with problem specifications, take these steps:

- [x] Run `bin/configlet sync -u -e <slug> --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

`Week | Featured at | exercise slug`

- [x] W43 | 2024-11-05 | eliuds-eggs #822
- [x] W44 | 2024-11-12 | collatz-conjecture #823
- [x] W45 | 2024-11-19 | run-length-encoding #824
- [x] W46 | 2024-11-26 | armstrong-numbers #825

- [x] W47 | 2024-12-03 | diamond #826
- [x] W48 | 2024-12-10 | largest-series-product #827

Exercises that are synced can be removed from these lists at will.

**Comment by mk-mxp** [comment]
When #48in24 started, the Exercism staff worked on exercise instructions to make them "more inclusive and engaging". That was the reason to **not** work on as many exercises as possible, but wait until about 14 days before the featured date.

Now Jeremy and Erik (the former staff) are no longer working full time for Exercism. And they worked through all of #48in24 to have that done before "leaving" (they are still active as volunteers).

So I think we can now update all the remaining #48in24 exercises without having outdated instructions / extra work for synchronising again. Still we should synchronize them before their feature date.

FYI @sarad1p1ty @fejan-malek @tomasnorre @homersimpsons

**Comment by mk-mxp** [comment]
@sarad1p1ty @fejan-malek @tomasnorre @homersimpsons

Looks like we are all done now. Thanks to all of you for contributing! You helped improving the 48 exercises featured in #48in24, and raised the quality experienced by thousands of students every year.

**Comment by homersimpsons** [comment]
Thanks to you @mk-mxp for all your work on this track!
